import NavBar from './componets/NavBar'
import Footer from './componets/footer'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ezeanwe Chigozie Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <NavBar/>
          {children}
          <Footer />
      </body>
    </html>
  )
}
